language: node_js
node_js:
- '12.22.10'
env:
  global:
  ## TOKEN REGISTRY
  - secure: z4Qq2uIU3MIz319GpgLNTt4rmm8MeVz2j9hcJqksGIAH1d5RqTTw7wZt9Au8M5xmD60rqAgM+kdHDEdVAv/y2oFoRM79Bd3Ce19EEwbgOYn5+1yI4R/wjWqyfkc+qLwUVB/aVH9bjUM51++wH9EIf4w2RnEwS/lAIOwGngzHErbHmQl/m1b6GQ6SoqYbJWqvM297+0ygRcM2qRRFG8o66QB7j0NSNvQboZFvBkuQAZsKz/TuLu+6tHbjF1jLzeZlXnvpprNuN9qcR4t/hPYsfwcpr7eUL6PSK1WlX7WV7hcCrSrVMJ2ckHPNLHVF3ZPRVIv7fR7xVv9A3Ee0hIZBGN9BFWfudamiaQJ+kBjzFQG8u5aRqJrKLzL1GAQqYjPe3Gk6FpIuhINjoMxFn8JNPObHfOvaknJc2VwJa1QHbQ01rCmMneYCulMVUeHYgsoJl/QWqaGs/f3B/ipEth/FyA54AQ00AE+OHr2cT9hvuEXkDUWuTXToDgM2SQOdLX2I6xc04+lBwHfVyWsNPsg8yRKqjMtA8s8osRMJ34rUJhzYT7Z3OGmKu2MYwIKstWA9Jck/drUcYf9rD8j9aMN5l7oCTnbRdLIqq8A58chWtWs54X1HhYt4AkDOPmg3Cz8MJRPdxo/gf5/vZxNAzmu5JNpTU8hswxkPbMvYE6ya+I8=

cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
# run the yarn travisDeployKey command to genrate this
# - openssl aes-256-cbc -K $encrypted_0b21ecdcf920_key -iv $encrypted_0b21ecdcf920_iv
#   -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
